- hosts: all
  become: true

  tasks:
    - name: stop website if running
      service:
        name: rangicus.service
        state: stopped

    - name: set hostname
      hostname:
        name: rangicus.xyz
        use: debian
    
    - name: apt update
      apt:
        autoclean: yes
        update_cache: yes

    - name: install git
      apt:
        name: git
        state: latest

    - name: update source
      git:
        repo: https://github.com/rangicus/rangicus.xyz.git
        dest: /opt/rangicus.xyz
        force: yes

    - name: npm install
      npm:
        path: /opt/rangicus.xyz
        state: present

    - name: build website
      command: npm run build
      args:
        chdir: /opt/rangicus.xyz

    - name: copy systemd service
      copy:
        src: /opt/rangicus.xyz/rangicus.service
        dest: /etc/systemd/system/rangicus.service
        remote_src: true

    - name: start website
      service:
        name: rangicus.service
        state: reloaded
        enabled: true
